sonar.typescript.lcov.reportPaths=coverage/frontend/lcov.info,coverage/backend/lcov.info
sonar.coverage.exclusions=**/node_modules/**,**/__tests__/**,**/*.test.js,**/*.test.jsx,**/*config*.js,**/*config*.mjs,**/models/**,backend/server.js,**/postcss.config.js,**/tailwind.config.js,**/vite.config.js,**/vitest.config.js,**/dist/**,**/shared/**
